//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Lib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NyanyaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NyanyaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Lib.NyanyaResources", typeof(NyanyaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A003.CommandBus CommandExcuteFaildException {0} {1} {2}..
        /// </summary>
        public static string Alert_CommandBus_CommandExcuteFaildException {
            get {
                return ResourceManager.GetString("Alert_CommandBus_CommandExcuteFaildException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A004.CommandService Unexpected Exception {0} {1} {2}..
        /// </summary>
        public static string Alert_CommandBus_UnexpectedException {
            get {
                return ResourceManager.GetString("Alert_CommandBus_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A008 ApplicationBusinessException {0}..
        /// </summary>
        public static string Alert_CommandHandlerBase_ApplicationBusinessException {
            get {
                return ResourceManager.GetString("Alert_CommandHandlerBase_ApplicationBusinessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A007 BusinessValidationFailedException {0}..
        /// </summary>
        public static string Alert_CommandHandlerBase_BusinessValidationFailedException {
            get {
                return ResourceManager.GetString("Alert_CommandHandlerBase_BusinessValidationFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A009 {0} {1}..
        /// </summary>
        public static string Alert_CommandHandlerBase_UnexpectedException {
            get {
                return ResourceManager.GetString("Alert_CommandHandlerBase_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A001.CommandService CommandExcuteFaildException {0} {1} {2}..
        /// </summary>
        public static string Alert_CommandService_CommandExcuteFaildException {
            get {
                return ResourceManager.GetString("Alert_CommandService_CommandExcuteFaildException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A002.CommandService Unexpected Exception {0} {1} {2}..
        /// </summary>
        public static string Alert_CommandService_UnexpectedException {
            get {
                return ResourceManager.GetString("Alert_CommandService_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A014.EventBus NEventStore_ConcurrencyException {0} {1} {2} {3}..
        /// </summary>
        public static string Alert_EventBus_NEventStore_ConcurrencyException {
            get {
                return ResourceManager.GetString("Alert_EventBus_NEventStore_ConcurrencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A005.EventBus Unexpected Exception {0} {1} {2} {3}..
        /// </summary>
        public static string Alert_EventBus_UnexpectedException {
            get {
                return ResourceManager.GetString("Alert_EventBus_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A006.EventDispatcher Unexpected Exception {0} {1} {2}..
        /// </summary>
        public static string Alert_EventDispatcher_UnexpectedException {
            get {
                return ResourceManager.GetString("Alert_EventDispatcher_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A011 ApplicationBusinessException {0}..
        /// </summary>
        public static string Alert_EventHandlerBase_ApplicationBusinessException {
            get {
                return ResourceManager.GetString("Alert_EventHandlerBase_ApplicationBusinessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A010 BusinessValidationFailedException {0}..
        /// </summary>
        public static string Alert_EventHandlerBase_BusinessValidationFailedException {
            get {
                return ResourceManager.GetString("Alert_EventHandlerBase_BusinessValidationFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A012 {0} {1}..
        /// </summary>
        public static string Alert_EventHandlerBase_UnexpectedException {
            get {
                return ResourceManager.GetString("Alert_EventHandlerBase_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A011 ApplicationBusinessException {0}..
        /// </summary>
        public static string Alert_JobScheduler_ApplicationBusinessException {
            get {
                return ResourceManager.GetString("Alert_JobScheduler_ApplicationBusinessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A020 BusinessValidationFailedException {0}..
        /// </summary>
        public static string Alert_JobScheduler_BusinessValidationFailedException {
            get {
                return ResourceManager.GetString("Alert_JobScheduler_BusinessValidationFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A022 {0} {1}..
        /// </summary>
        public static string Alert_JobScheduler_UnexpectedException {
            get {
                return ResourceManager.GetString("Alert_JobScheduler_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A013 Yilian Request Sending Faild {0}..
        /// </summary>
        public static string Alert_YilianGateway_RequestSendingFailed {
            get {
                return ResourceManager.GetString("Alert_YilianGateway_RequestSendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &amp;apos;{0}&amp;apos; cannot be null, empty or contain only white space..
        /// </summary>
        public static string ArgumentIsNullOrWhitespace {
            get {
                return ResourceManager.GetString("ArgumentIsNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The associated metadata type for type &amp;apos;{0}&amp;apos; contains the following unknown properties or fields: {1}. Please make sure that the names of these members match the names of the properties on the main type..
        /// </summary>
        public static string AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties {
            get {
                return ResourceManager.GetString("AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &amp;apos;{0}&amp;apos; must be public..
        /// </summary>
        public static string AttributeStore_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("AttributeStore_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &amp;apos;{0}&amp;apos; does not contain a public method named &amp;apos;{1}&amp;apos;..
        /// </summary>
        public static string AttributeStore_Unknown_Method {
            get {
                return ResourceManager.GetString("AttributeStore_Unknown_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &amp;apos;{0}&amp;apos; does not contain a public property named &amp;apos;{1}&amp;apos;..
        /// </summary>
        public static string AttributeStore_Unknown_Property {
            get {
                return ResourceManager.GetString("AttributeStore_Unknown_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field value is not available..
        /// </summary>
        public static string AvailableValuesAttribute_AvailableValuesAttribute_ValueNotAvailable {
            get {
                return ResourceManager.GetString("AvailableValuesAttribute_AvailableValuesAttribute_ValueNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E016.CommandService CommandExcuteFaildException {0} {1} {2}..
        /// </summary>
        public static string CommandBus_CommandExcuteFaildException {
            get {
                return ResourceManager.GetString("CommandBus_CommandExcuteFaildException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E001.CommandService Unexpected Exception {0} {1} {2}..
        /// </summary>
        public static string CommandBus_UnexpectedException {
            get {
                return ResourceManager.GetString("CommandBus_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E017.CommandService WebServiceException {0} {1} {2} {3}..
        /// </summary>
        public static string CommandBus_WebServiceException {
            get {
                return ResourceManager.GetString("CommandBus_WebServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E008 ApplicationBusinessException {0}..
        /// </summary>
        public static string CommandHandlerBase_ApplicationBusinessException {
            get {
                return ResourceManager.GetString("CommandHandlerBase_ApplicationBusinessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E006 BusinessConcurrenceException {0}..
        /// </summary>
        public static string CommandHandlerBase_BusinessConcurrenceException {
            get {
                return ResourceManager.GetString("CommandHandlerBase_BusinessConcurrenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E007 BusinessValidationFailedException {0}..
        /// </summary>
        public static string CommandHandlerBase_BusinessValidationFailedException {
            get {
                return ResourceManager.GetString("CommandHandlerBase_BusinessValidationFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E004 DbUpdateConcurrencyException {0}..
        /// </summary>
        public static string CommandHandlerBase_DbUpdateConcurrencyException {
            get {
                return ResourceManager.GetString("CommandHandlerBase_DbUpdateConcurrencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E005 DbUpdateException {0}..
        /// </summary>
        public static string CommandHandlerBase_DbUpdateException {
            get {
                return ResourceManager.GetString("CommandHandlerBase_DbUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E009 {0} {1}..
        /// </summary>
        public static string CommandHandlerBase_UnexpectedException {
            get {
                return ResourceManager.GetString("CommandHandlerBase_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find command handler for {0}..
        /// </summary>
        public static string CommandService_CanNotFindCommandHandler {
            get {
                return ResourceManager.GetString("CommandService_CanNotFindCommandHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        public static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0}.{1} could not be found..
        /// </summary>
        public static string Common_PropertyNotFound {
            get {
                return ResourceManager.GetString("Common_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} must derive from {1}..
        /// </summary>
        public static string Common_TypeMustDriveFromType {
            get {
                return ResourceManager.GetString("Common_TypeMustDriveFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;apos;{0}&amp;apos; and &amp;apos;{1}&amp;apos; do not match..
        /// </summary>
        public static string CompareAttribute_MustMatch {
            get {
                return ResourceManager.GetString("CompareAttribute_MustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a property named {0}..
        /// </summary>
        public static string CompareAttribute_UnknownProperty {
            get {
                return ResourceManager.GetString("CompareAttribute_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C001.Can not find CommandBus command processor address..
        /// </summary>
        public static string Config_CommandBus_001 {
            get {
                return ResourceManager.GetString("Config_CommandBus_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid credit card number..
        /// </summary>
        public static string CreditCardAttribute_Invalid {
            get {
                return ResourceManager.GetString("CreditCardAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute method &amp;apos;{0}&amp;apos; in type &amp;apos;{1}&amp;apos; must return System.ComponentModel.DataAnnotations.ValidationResult.  Use System.ComponentModel.DataAnnotations.ValidationResult.Success to represent success..
        /// </summary>
        public static string CustomValidationAttribute_Method_Must_Return_ValidationResult {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Must_Return_ValidationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute method &amp;apos;{0}&amp;apos; does not exist in type &amp;apos;{1}&amp;apos; or is not public and static..
        /// </summary>
        public static string CustomValidationAttribute_Method_Not_Found {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute.Method was not specified..
        /// </summary>
        public static string CustomValidationAttribute_Method_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute method &amp;apos;{0}&amp;apos; in type &amp;apos;{1}&amp;apos; must match the expected signature: public static ValidationResult {0}(object value, ValidationContext context).  The value can be strongly typed.  The ValidationContext parameter is optional..
        /// </summary>
        public static string CustomValidationAttribute_Method_Signature {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert the value of type &amp;apos;{0}&amp;apos; to &amp;apos;{1}&amp;apos; as expected by method {2}.{3}..
        /// </summary>
        public static string CustomValidationAttribute_Type_Conversion_Failed {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Conversion_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom validation type &amp;apos;{0}&amp;apos; must be public..
        /// </summary>
        public static string CustomValidationAttribute_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid..
        /// </summary>
        public static string CustomValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CustomValidationAttribute.ValidatorType was not specified..
        /// </summary>
        public static string CustomValidationAttribute_ValidatorType_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidatorType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom DataType string cannot be null or empty..
        /// </summary>
        public static string DataTypeAttribute_EmptyDataTypeString {
            get {
                return ResourceManager.GetString("DataTypeAttribute_EmptyDataTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} property has not been set.  Use the {1} method to get the value..
        /// </summary>
        public static string DisplayAttribute_PropertyNotSet {
            get {
                return ResourceManager.GetString("DisplayAttribute_PropertyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid e-mail address..
        /// </summary>
        public static string EmailAddressAttribute_Invalid {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type provided for EnumDataTypeAttribute cannot be null..
        /// </summary>
        public static string EnumDataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &amp;apos;{0}&amp;apos; needs to represent an enumeration type..
        /// </summary>
        public static string EnumDataTypeAttribute_TypeNeedsToBeAnEnum {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeNeedsToBeAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E016.EventBus NEventStore_ConcurrencyException {0} {1} {2} {3}..
        /// </summary>
        public static string EventBus_NEventStore_ConcurrencyException {
            get {
                return ResourceManager.GetString("EventBus_NEventStore_ConcurrencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E002.EventBus Unexpected Exception {0} {1} {2} {3}..
        /// </summary>
        public static string EventBus_UnexpectedException {
            get {
                return ResourceManager.GetString("EventBus_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E003.EventDispatcher Unexpected Exception {0} {1} {2}..
        /// </summary>
        public static string EventDispatcher_UnexpectedException {
            get {
                return ResourceManager.GetString("EventDispatcher_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E014 ApplicationBusinessException {0}..
        /// </summary>
        public static string EventHandlerBase_ApplicationBusinessException {
            get {
                return ResourceManager.GetString("EventHandlerBase_ApplicationBusinessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E012 BusinessConcurrenceException {0}..
        /// </summary>
        public static string EventHandlerBase_BusinessConcurrenceException {
            get {
                return ResourceManager.GetString("EventHandlerBase_BusinessConcurrenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E013 BusinessValidationFailedException {0}..
        /// </summary>
        public static string EventHandlerBase_BusinessValidationFailedException {
            get {
                return ResourceManager.GetString("EventHandlerBase_BusinessValidationFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E010 DbUpdateConcurrencyException {0}..
        /// </summary>
        public static string EventHandlerBase_DbUpdateConcurrencyException {
            get {
                return ResourceManager.GetString("EventHandlerBase_DbUpdateConcurrencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E011 DbUpdateException {0}..
        /// </summary>
        public static string EventHandlerBase_DbUpdateException {
            get {
                return ResourceManager.GetString("EventHandlerBase_DbUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E015 {0} {1}..
        /// </summary>
        public static string EventHandlerBase_UnexpectedException {
            get {
                return ResourceManager.GetString("EventHandlerBase_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field only accepts files with the following extensions: {1}..
        /// </summary>
        public static string FileExtensionsAttribute_Invalid {
            get {
                return ResourceManager.GetString("FileExtensionsAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 银行卡信息错误.
        /// </summary>
        public static string InvestingRequest_BankCardNo_InfoError {
            get {
                return ResourceManager.GetString("InvestingRequest_BankCardNo_InfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品份额错误.
        /// </summary>
        public static string InvestingRequest_Count_InfoError {
            get {
                return ResourceManager.GetString("InvestingRequest_Count_InfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J012 BusinessConcurrenceException {0}..
        /// </summary>
        public static string JobScheduler_BusinessConcurrenceException {
            get {
                return ResourceManager.GetString("JobScheduler_BusinessConcurrenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J013 BusinessValidationFailedException {0}..
        /// </summary>
        public static string JobScheduler_BusinessValidationFailedException {
            get {
                return ResourceManager.GetString("JobScheduler_BusinessValidationFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J010 DbUpdateConcurrencyException {0}..
        /// </summary>
        public static string JobScheduler_DbUpdateConcurrencyException {
            get {
                return ResourceManager.GetString("JobScheduler_DbUpdateConcurrencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J011 DbUpdateException {0}..
        /// </summary>
        public static string JobScheduler_DbUpdateException {
            get {
                return ResourceManager.GetString("JobScheduler_DbUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J015 {0} {1}..
        /// </summary>
        public static string JobScheduler_UnexpectedException {
            get {
                return ResourceManager.GetString("JobScheduler_UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve property &amp;apos;{0}&amp;apos; because localization failed.  Type &amp;apos;{1}&amp;apos; is not public or does not contain a public static string property with the name &amp;apos;{2}&amp;apos;..
        /// </summary>
        public static string LocalizableString_LocalizationFailed {
            get {
                return ResourceManager.GetString("LocalizableString_LocalizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxLengthAttribute must have a Length value that is greater than zero. Use MaxLength() without parameters to indicate that the string or array can have the maximum allowable length..
        /// </summary>
        public static string MaxLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string or array type with a maximum length of &amp;apos;{1}&amp;apos;..
        /// </summary>
        public static string MaxLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetadataClassType cannot be null..
        /// </summary>
        public static string MetadataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("MetadataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinLengthAttribute must have a Length value that is zero or greater..
        /// </summary>
        public static string MinLengthAttribute_InvalidMinLength {
            get {
                return ResourceManager.GetString("MinLengthAttribute_InvalidMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string or array type with a minimum length of &amp;apos;{1}&amp;apos;..
        /// </summary>
        public static string MinLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid phone number..
        /// </summary>
        public static string PhoneAttribute_Invalid {
            get {
                return ResourceManager.GetString("PhoneAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} must implement {1}..
        /// </summary>
        public static string RangeAttribute_ArbitraryTypeNotIComparable {
            get {
                return ResourceManager.GetString("RangeAttribute_ArbitraryTypeNotIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum value &amp;apos;{0}&amp;apos; must be greater than or equal to the minimum value &amp;apos;{1}&amp;apos;..
        /// </summary>
        public static string RangeAttribute_MinGreaterThanMax {
            get {
                return ResourceManager.GetString("RangeAttribute_MinGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum and maximum values must be set..
        /// </summary>
        public static string RangeAttribute_Must_Set_Min_And_Max {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Min_And_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OperandType must be set when strings are used for minimum and maximum values..
        /// </summary>
        public static string RangeAttribute_Must_Set_Operand_Type {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Operand_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between {1} and {2}..
        /// </summary>
        public static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must match the regular expression &amp;apos;{1}&amp;apos;..
        /// </summary>
        public static string RegexAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RegexAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pattern must be set to a valid regular expression..
        /// </summary>
        public static string RegularExpressionAttribute_Empty_Pattern {
            get {
                return ResourceManager.GetString("RegularExpressionAttribute_Empty_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录密码为6~18位数字和字母的组合，区分大小写.
        /// </summary>
        public static string RequestValidationMessage_PasswordFormatError {
            get {
                return ResourceManager.GetString("RequestValidationMessage_PasswordFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户名或密码错误，请重新输入。.
        /// </summary>
        public static string RequestValidationMessage_PasswordFormatError_SignIn {
            get {
                return ResourceManager.GetString("RequestValidationMessage_PasswordFormatError_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支付密码为8~18位，数字和字母的组合，区分大小写.
        /// </summary>
        public static string RequestValidationMessage_PaymentPasswordFormatError {
            get {
                return ResourceManager.GetString("RequestValidationMessage_PaymentPasswordFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-18位字母、数字或符号(~!@#$%^&amp;*_)组合，区分大小写。.
        /// </summary>
        public static string RequestValidationMessage_xy_PasswordFormatError {
            get {
                return ResourceManager.GetString("RequestValidationMessage_xy_PasswordFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-18位字母、数字和符号(~!@#$%^&amp;*_)组合，区分大小写。.
        /// </summary>
        public static string RequestValidationMessage_xy_PaymentPasswordFormatError {
            get {
                return ResourceManager.GetString("RequestValidationMessage_xy_PaymentPasswordFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请填写有效手机号.
        /// </summary>
        public static string RequetValidationMessage_CellphoneFormatError {
            get {
                return ResourceManager.GetString("RequetValidationMessage_CellphoneFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您尾号为{0}的借记卡绑定失败!失败原因：{1}。如需帮助 4008-556-333.
        /// </summary>
        public static string Sms_AddBankCardFailed {
            get {
                return ResourceManager.GetString("Sms_AddBankCardFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您尾号为{0}的借记卡已经绑定成功!现在即可开始购买。关注金银猫官方微信，200元本金券等你拿。如需帮助 4008-556-333.
        /// </summary>
        public static string Sms_AddBankCardSuccessed {
            get {
                return ResourceManager.GetString("Sms_AddBankCardSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您已购买成功{0}，订单号：{1}，订单金额{2}元。如需帮助4008556333。.
        /// </summary>
        public static string Sms_PaidForOrder {
            get {
                return ResourceManager.GetString("Sms_PaidForOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购买失败{0}，订单号：{1}，订单金额{2}元。失败原因：{3}。如需帮助 4008556333.
        /// </summary>
        public static string Sms_PaidForOrderFailed {
            get {
                return ResourceManager.GetString("Sms_PaidForOrderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您购买的{0}已操作还款，本息共{1}元近期归还至您的银行卡上。.
        /// </summary>
        public static string Sms_ProductRepaid {
            get {
                return ResourceManager.GetString("Sms_ProductRepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 恭喜您成功注册金银猫！关注金银猫官方微信，200元本金券等你拿。如需帮助请致电金银猫客服 4008556333.
        /// </summary>
        public static string Sms_SignUpSuccessful {
            get {
                return ResourceManager.GetString("Sms_SignUpSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您用于金银猫的验证码为 {0}，{1}分钟内有效。为了账户安全，勿向他人透露此内容。如需帮助 4008556333.
        /// </summary>
        public static string Sms_VeriCode {
            get {
                return ResourceManager.GetString("Sms_VeriCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您尾号为{0}的储蓄卡绑定失败!失败原因：{1}。如需帮助，请致电4008556333。.
        /// </summary>
        public static string Sms_xy_AddBankCardFailed {
            get {
                return ResourceManager.GetString("Sms_xy_AddBankCardFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您尾号为{0}的储蓄卡已经绑定成功!现在即可开始购买。如需帮助，请致电4008556333。.
        /// </summary>
        public static string Sms_xy_AddBankCardSuccessed {
            get {
                return ResourceManager.GetString("Sms_xy_AddBankCardSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 购买成功，订单号：{0}，订单金额{1}元。如需帮助，请致电4008556333。.
        /// </summary>
        public static string Sms_xy_PaidForOrder {
            get {
                return ResourceManager.GetString("Sms_xy_PaidForOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的订单{0}，订单金额{1}元交易失败。失败原因：{2}，如需帮助，请致电4008556333。.
        /// </summary>
        public static string Sms_xy_PaidForOrderFailed {
            get {
                return ResourceManager.GetString("Sms_xy_PaidForOrderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您购买的{0}今天已还款，本息共{1}元已归还至您尾号为{2}的卡上。感谢您对兴业票产品的支持！.
        /// </summary>
        public static string Sms_xy_ProductHasRepaid {
            get {
                return ResourceManager.GetString("Sms_xy_ProductHasRepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您购买的{0}今天已结息，本息共{1}元将在三个工作日内归还至您尾号为{2}的{3}银行卡上。.
        /// </summary>
        public static string Sms_xy_ProductRepaid {
            get {
                return ResourceManager.GetString("Sms_xy_ProductRepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 恭喜您成功注册兴业票！请注意保护好您的密码。如需帮助，请致电4008556333。.
        /// </summary>
        public static string Sms_xy_SignUpSuccessful {
            get {
                return ResourceManager.GetString("Sms_xy_SignUpSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的兴业票校验码为{0}，{1}分钟内有效。为了账户安全，勿向他人透露此内容。如需帮助，请致电4008556333。.
        /// </summary>
        public static string Sms_xy_VeriCode {
            get {
                return ResourceManager.GetString("Sms_xy_VeriCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;金包银&quot;项目提现款已打出，本息共{0}元近期归还至您尾号为{1}的{2}银行卡上。感谢您对金银猫产品的支持！.
        /// </summary>
        public static string Sms_ZCBRedeemBillResult {
            get {
                return ResourceManager.GetString("Sms_ZCBRedeemBillResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length must be a nonnegative integer..
        /// </summary>
        public static string StringLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("StringLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a maximum length of {1}..
        /// </summary>
        public static string StringLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a minimum length of {2} and a maximum length of {1}..
        /// </summary>
        public static string StringLengthAttribute_ValidationErrorIncludingMinimum {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationErrorIncludingMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key parameter at position {0} with value &amp;apos;{1}&amp;apos; is not a string. Every key control parameter must be a string..
        /// </summary>
        public static string UIHintImplementation_ControlParameterKeyIsNotAString {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyIsNotAString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key parameter at position {0} is null. Every key control parameter must be a string..
        /// </summary>
        public static string UIHintImplementation_ControlParameterKeyIsNull {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key parameter at position {0} with value &amp;apos;{1}&amp;apos; occurs more than once..
        /// </summary>
        public static string UIHintImplementation_ControlParameterKeyOccursMoreThanOnce {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyOccursMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of control parameters must be even..
        /// </summary>
        public static string UIHintImplementation_NeedEvenNumberOfControlParameters {
            get {
                return ResourceManager.GetString("UIHintImplementation_NeedEvenNumberOfControlParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid fully-qualified http, https, or ftp URL..
        /// </summary>
        public static string UrlAttribute_Invalid {
            get {
                return ResourceManager.GetString("UrlAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either ErrorMessageString or ErrorMessageResourceName must be set, but not both..
        /// </summary>
        public static string ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource {
            get {
                return ResourceManager.GetString("ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsValid(object value) has not been implemented by this class.  The preferred entry point is GetValidationResult() and classes should override IsValid(object value, ValidationContext context)..
        /// </summary>
        public static string ValidationAttribute_IsValid_NotImplemented {
            get {
                return ResourceManager.GetString("ValidationAttribute_IsValid_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both ErrorMessageResourceType and ErrorMessageResourceName need to be set on this attribute..
        /// </summary>
        public static string ValidationAttribute_NeedBothResourceTypeAndResourceName {
            get {
                return ResourceManager.GetString("ValidationAttribute_NeedBothResourceTypeAndResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &amp;apos;{0}&amp;apos; on resource type &amp;apos;{1}&amp;apos; is not a string type..
        /// </summary>
        public static string ValidationAttribute_ResourcePropertyNotStringType {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourcePropertyNotStringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource type &amp;apos;{0}&amp;apos; does not have an accessible static property named &amp;apos;{1}&amp;apos;..
        /// </summary>
        public static string ValidationAttribute_ResourceTypeDoesNotHaveProperty {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourceTypeDoesNotHaveProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is invalid..
        /// </summary>
        public static string ValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("ValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ValidationContext for the type &amp;apos;{0}&amp;apos;, member name &amp;apos;{1}&amp;apos; must provide the MethodInfo..
        /// </summary>
        public static string ValidationContext_Must_Be_Method {
            get {
                return ResourceManager.GetString("ValidationContext_Must_Be_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service of type &amp;apos;{0}&amp;apos; already exists in the container..
        /// </summary>
        public static string ValidationContextServiceContainer_ItemAlreadyExists {
            get {
                return ResourceManager.GetString("ValidationContextServiceContainer_ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instance provided must match the ObjectInstance on the ValidationContext supplied..
        /// </summary>
        public static string Validator_InstanceMustMatchValidationContextInstance {
            get {
                return ResourceManager.GetString("Validator_InstanceMustMatchValidationContextInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for property &amp;apos;{0}&amp;apos; must be of type &amp;apos;{1}&amp;apos;..
        /// </summary>
        public static string Validator_Property_Value_Wrong_Type {
            get {
                return ResourceManager.GetString("Validator_Property_Value_Wrong_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G001 Yilian Request Sending Faild {0}..
        /// </summary>
        public static string YilianGateway_RequestSendingFailed {
            get {
                return ResourceManager.GetString("YilianGateway_RequestSendingFailed", resourceCulture);
            }
        }
    }
}
