//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 414
#pragma warning disable 649
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace Yuyi.Jinyinmao.Domain.EventProcessor
{
    using Orleans;
    using System;
    using System.Runtime.InteropServices;
    using System.Runtime.Serialization;
    
}
namespace Yuyi.Jinyinmao.Domain.Events
{
    using Orleans;
    using System;
    using System.Runtime.InteropServices;
    using System.Runtime.Serialization;
    
}
namespace Yuyi.Jinyinmao.Domain.Misc
{
    using Orleans;
    using System;
    using System.Runtime.InteropServices;
    using System.Runtime.Serialization;
    
}
namespace Yuyi.Jinyinmao.Domain
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using Orleans;
    using System.Runtime.InteropServices;
    using System.Runtime.Serialization;
    using Yuyi.Jinyinmao.Domain.Dtos;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.9.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("Yuyi.Jinyinmao.Domain.Cellphone")]
    public class CellphoneState : global::Orleans.GrainState, ICellphoneState
    {
        

            public String @Cellphone { get; set; }

            public Boolean @Registered { get; set; }

            public Nullable<Guid> @UserId { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("Cellphone", out value)) @Cellphone = (String) value;
                if (values.TryGetValue("Registered", out value)) @Registered = (Boolean) value;
                if (values.TryGetValue("UserId", out value)) @UserId = (Nullable<Guid>) value;
            }

            public override System.String ToString()
            {
                return System.String.Format("CellphoneState( Cellphone={0} Registered={1} UserId={2} )", @Cellphone, @Registered, @UserId);
            }
        
        public CellphoneState() : 
                base("Yuyi.Jinyinmao.Domain.Cellphone")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["Cellphone"] = this.Cellphone;
            result["Registered"] = this.Registered;
            result["UserId"] = this.UserId;
            return result;
        }
        
        private void InitStateFields()
        {
            this.Cellphone = default(String);
            this.Registered = default(Boolean);
            this.UserId = default(Nullable<Guid>);
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            CellphoneState input = ((CellphoneState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            CellphoneState input = ((CellphoneState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            CellphoneState result = new CellphoneState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.9.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("Yuyi.Jinyinmao.Domain.RegularProduct")]
    public class RegularProductState : global::Orleans.GrainState, IRegularProductState
    {
        

            public String @Agreement1 { get; set; }

            public String @Agreement2 { get; set; }

            public Dictionary<String,Object> @Args { get; set; }

            public String @BankName { get; set; }

            public String @Drawee { get; set; }

            public String @DraweeInfo { get; set; }

            public String @EndorseImageLink { get; set; }

            public DateTime @EndSellTime { get; set; }

            public String @EnterpriseInfo { get; set; }

            public String @EnterpriseLicense { get; set; }

            public String @EnterpriseName { get; set; }

            public Int64 @FinancingSumAmount { get; set; }

            public Int32 @IssueNo { get; set; }

            public DateTime @IssueTime { get; set; }

            public Dictionary<Guid,OrderInfo> @Orders { get; set; }

            public Int32 @Period { get; set; }

            public String @PledgeNo { get; set; }

            public Int64 @ProductCategory { get; set; }

            public Guid @ProductId { get; set; }

            public String @ProductName { get; set; }

            public String @ProductNo { get; set; }

            public Boolean @Repaid { get; set; }

            public Nullable<DateTime> @RepaidTime { get; set; }

            public DateTime @RepaymentDeadline { get; set; }

            public String @RiskManagement { get; set; }

            public String @RiskManagementInfo { get; set; }

            public String @RiskManagementMode { get; set; }

            public DateTime @SettleDate { get; set; }

            public Boolean @SoldOut { get; set; }

            public Nullable<DateTime> @SoldOutTime { get; set; }

            public DateTime @StartSellTime { get; set; }

            public Int32 @UnitPrice { get; set; }

            public String @Usage { get; set; }

            public Nullable<DateTime> @ValueDate { get; set; }

            public Nullable<Int32> @ValueDateMode { get; set; }

            public Int32 @Yield { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("Agreement1", out value)) @Agreement1 = (String) value;
                if (values.TryGetValue("Agreement2", out value)) @Agreement2 = (String) value;
                if (values.TryGetValue("Args", out value)) @Args = (Dictionary<String,Object>) value;
                if (values.TryGetValue("BankName", out value)) @BankName = (String) value;
                if (values.TryGetValue("Drawee", out value)) @Drawee = (String) value;
                if (values.TryGetValue("DraweeInfo", out value)) @DraweeInfo = (String) value;
                if (values.TryGetValue("EndorseImageLink", out value)) @EndorseImageLink = (String) value;
                if (values.TryGetValue("EndSellTime", out value)) @EndSellTime = (DateTime) value;
                if (values.TryGetValue("EnterpriseInfo", out value)) @EnterpriseInfo = (String) value;
                if (values.TryGetValue("EnterpriseLicense", out value)) @EnterpriseLicense = (String) value;
                if (values.TryGetValue("EnterpriseName", out value)) @EnterpriseName = (String) value;
                if (values.TryGetValue("FinancingSumAmount", out value)) @FinancingSumAmount = value is Int32 ? (Int32)value : (Int64)value;
                if (values.TryGetValue("IssueNo", out value)) @IssueNo = value is Int64 ? (Int32)(Int64)value : (Int32)value;
                if (values.TryGetValue("IssueTime", out value)) @IssueTime = (DateTime) value;
                if (values.TryGetValue("Orders", out value)) @Orders = (Dictionary<Guid,OrderInfo>) value;
                if (values.TryGetValue("Period", out value)) @Period = value is Int64 ? (Int32)(Int64)value : (Int32)value;
                if (values.TryGetValue("PledgeNo", out value)) @PledgeNo = (String) value;
                if (values.TryGetValue("ProductCategory", out value)) @ProductCategory = value is Int32 ? (Int32)value : (Int64)value;
                if (values.TryGetValue("ProductId", out value)) @ProductId = (Guid) value;
                if (values.TryGetValue("ProductName", out value)) @ProductName = (String) value;
                if (values.TryGetValue("ProductNo", out value)) @ProductNo = (String) value;
                if (values.TryGetValue("Repaid", out value)) @Repaid = (Boolean) value;
                if (values.TryGetValue("RepaidTime", out value)) @RepaidTime = (Nullable<DateTime>) value;
                if (values.TryGetValue("RepaymentDeadline", out value)) @RepaymentDeadline = (DateTime) value;
                if (values.TryGetValue("RiskManagement", out value)) @RiskManagement = (String) value;
                if (values.TryGetValue("RiskManagementInfo", out value)) @RiskManagementInfo = (String) value;
                if (values.TryGetValue("RiskManagementMode", out value)) @RiskManagementMode = (String) value;
                if (values.TryGetValue("SettleDate", out value)) @SettleDate = (DateTime) value;
                if (values.TryGetValue("SoldOut", out value)) @SoldOut = (Boolean) value;
                if (values.TryGetValue("SoldOutTime", out value)) @SoldOutTime = (Nullable<DateTime>) value;
                if (values.TryGetValue("StartSellTime", out value)) @StartSellTime = (DateTime) value;
                if (values.TryGetValue("UnitPrice", out value)) @UnitPrice = value is Int64 ? (Int32)(Int64)value : (Int32)value;
                if (values.TryGetValue("Usage", out value)) @Usage = (String) value;
                if (values.TryGetValue("ValueDate", out value)) @ValueDate = (Nullable<DateTime>) value;
                if (values.TryGetValue("ValueDateMode", out value)) @ValueDateMode = (Nullable<Int32>) value;
                if (values.TryGetValue("Yield", out value)) @Yield = value is Int64 ? (Int32)(Int64)value : (Int32)value;
            }

            public override System.String ToString()
            {
                return System.String.Format("RegularProductState( Agreement1={0} Agreement2={1} Args={2} BankName={3} Drawee={4} DraweeInfo={5} EndorseImageLink={6} EndSellTime={7} EnterpriseInfo={8} EnterpriseLicense={9} EnterpriseName={10} FinancingSumAmount={11} IssueNo={12} IssueTime={13} Orders={14} Period={15} PledgeNo={16} ProductCategory={17} ProductId={18} ProductName={19} ProductNo={20} Repaid={21} RepaidTime={22} RepaymentDeadline={23} RiskManagement={24} RiskManagementInfo={25} RiskManagementMode={26} SettleDate={27} SoldOut={28} SoldOutTime={29} StartSellTime={30} UnitPrice={31} Usage={32} ValueDate={33} ValueDateMode={34} Yield={35} )", @Agreement1, @Agreement2, @Args, @BankName, @Drawee, @DraweeInfo, @EndorseImageLink, @EndSellTime, @EnterpriseInfo, @EnterpriseLicense, @EnterpriseName, @FinancingSumAmount, @IssueNo, @IssueTime, @Orders, @Period, @PledgeNo, @ProductCategory, @ProductId, @ProductName, @ProductNo, @Repaid, @RepaidTime, @RepaymentDeadline, @RiskManagement, @RiskManagementInfo, @RiskManagementMode, @SettleDate, @SoldOut, @SoldOutTime, @StartSellTime, @UnitPrice, @Usage, @ValueDate, @ValueDateMode, @Yield);
            }
        
        public RegularProductState() : 
                base("Yuyi.Jinyinmao.Domain.RegularProduct")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["Agreement1"] = this.Agreement1;
            result["Agreement2"] = this.Agreement2;
            result["Args"] = this.Args;
            result["BankName"] = this.BankName;
            result["Drawee"] = this.Drawee;
            result["DraweeInfo"] = this.DraweeInfo;
            result["EndorseImageLink"] = this.EndorseImageLink;
            result["EndSellTime"] = this.EndSellTime;
            result["EnterpriseInfo"] = this.EnterpriseInfo;
            result["EnterpriseLicense"] = this.EnterpriseLicense;
            result["EnterpriseName"] = this.EnterpriseName;
            result["FinancingSumAmount"] = this.FinancingSumAmount;
            result["IssueNo"] = this.IssueNo;
            result["IssueTime"] = this.IssueTime;
            result["Orders"] = this.Orders;
            result["Period"] = this.Period;
            result["PledgeNo"] = this.PledgeNo;
            result["ProductCategory"] = this.ProductCategory;
            result["ProductId"] = this.ProductId;
            result["ProductName"] = this.ProductName;
            result["ProductNo"] = this.ProductNo;
            result["Repaid"] = this.Repaid;
            result["RepaidTime"] = this.RepaidTime;
            result["RepaymentDeadline"] = this.RepaymentDeadline;
            result["RiskManagement"] = this.RiskManagement;
            result["RiskManagementInfo"] = this.RiskManagementInfo;
            result["RiskManagementMode"] = this.RiskManagementMode;
            result["SettleDate"] = this.SettleDate;
            result["SoldOut"] = this.SoldOut;
            result["SoldOutTime"] = this.SoldOutTime;
            result["StartSellTime"] = this.StartSellTime;
            result["UnitPrice"] = this.UnitPrice;
            result["Usage"] = this.Usage;
            result["ValueDate"] = this.ValueDate;
            result["ValueDateMode"] = this.ValueDateMode;
            result["Yield"] = this.Yield;
            return result;
        }
        
        private void InitStateFields()
        {
            this.Agreement1 = default(String);
            this.Agreement2 = default(String);
            this.Args = new Dictionary<String,Object>();
            this.BankName = default(String);
            this.Drawee = default(String);
            this.DraweeInfo = default(String);
            this.EndorseImageLink = default(String);
            this.EndSellTime = default(DateTime);
            this.EnterpriseInfo = default(String);
            this.EnterpriseLicense = default(String);
            this.EnterpriseName = default(String);
            this.FinancingSumAmount = default(Int64);
            this.IssueNo = default(Int32);
            this.IssueTime = default(DateTime);
            this.Orders = new Dictionary<Guid,OrderInfo>();
            this.Period = default(Int32);
            this.PledgeNo = default(String);
            this.ProductCategory = default(Int64);
            this.ProductId = default(Guid);
            this.ProductName = default(String);
            this.ProductNo = default(String);
            this.Repaid = default(Boolean);
            this.RepaidTime = default(Nullable<DateTime>);
            this.RepaymentDeadline = default(DateTime);
            this.RiskManagement = default(String);
            this.RiskManagementInfo = default(String);
            this.RiskManagementMode = default(String);
            this.SettleDate = default(DateTime);
            this.SoldOut = default(Boolean);
            this.SoldOutTime = default(Nullable<DateTime>);
            this.StartSellTime = default(DateTime);
            this.UnitPrice = default(Int32);
            this.Usage = default(String);
            this.ValueDate = default(Nullable<DateTime>);
            this.ValueDateMode = default(Nullable<Int32>);
            this.Yield = default(Int32);
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            RegularProductState input = ((RegularProductState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            RegularProductState input = ((RegularProductState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            RegularProductState result = new RegularProductState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.9.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("Yuyi.Jinyinmao.Domain.User")]
    public class UserState : global::Orleans.GrainState, IUserState
    {
        

            public Dictionary<String,Object> @Args { get; set; }

            public Dictionary<String,BankCard> @BankCards { get; set; }

            public String @Cellphone { get; set; }

            public Int64 @ClientType { get; set; }

            public Boolean @Closed { get; set; }

            public Int64 @ContractId { get; set; }

            public Credential @Credential { get; set; }

            public String @CredentialNo { get; set; }

            public String @EncryptedPassword { get; set; }

            public String @EncryptedPaymentPassword { get; set; }

            public String @InviteBy { get; set; }

            public Dictionary<Guid,JBYAccountTransaction> @JBYAccount { get; set; }

            public List<String> @LoginNames { get; set; }

            public Dictionary<Guid,Order> @Orders { get; set; }

            public String @OutletCode { get; set; }

            public String @PaymentSalt { get; set; }

            public String @RealName { get; set; }

            public DateTime @RegisterTime { get; set; }

            public String @Salt { get; set; }

            public Dictionary<Guid,SettleAccountTransaction> @SettleAccount { get; set; }

            public Guid @UserId { get; set; }

            public Boolean @Verified { get; set; }

            public Nullable<DateTime> @VerifiedTime { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("Args", out value)) @Args = (Dictionary<String,Object>) value;
                if (values.TryGetValue("BankCards", out value)) @BankCards = (Dictionary<String,BankCard>) value;
                if (values.TryGetValue("Cellphone", out value)) @Cellphone = (String) value;
                if (values.TryGetValue("ClientType", out value)) @ClientType = value is Int32 ? (Int32)value : (Int64)value;
                if (values.TryGetValue("Closed", out value)) @Closed = (Boolean) value;
                if (values.TryGetValue("ContractId", out value)) @ContractId = value is Int32 ? (Int32)value : (Int64)value;
                if (values.TryGetValue("Credential", out value)) @Credential = (Credential) value;
                if (values.TryGetValue("CredentialNo", out value)) @CredentialNo = (String) value;
                if (values.TryGetValue("EncryptedPassword", out value)) @EncryptedPassword = (String) value;
                if (values.TryGetValue("EncryptedPaymentPassword", out value)) @EncryptedPaymentPassword = (String) value;
                if (values.TryGetValue("InviteBy", out value)) @InviteBy = (String) value;
                if (values.TryGetValue("JBYAccount", out value)) @JBYAccount = (Dictionary<Guid,JBYAccountTransaction>) value;
                if (values.TryGetValue("LoginNames", out value)) @LoginNames = (List<String>) value;
                if (values.TryGetValue("Orders", out value)) @Orders = (Dictionary<Guid,Order>) value;
                if (values.TryGetValue("OutletCode", out value)) @OutletCode = (String) value;
                if (values.TryGetValue("PaymentSalt", out value)) @PaymentSalt = (String) value;
                if (values.TryGetValue("RealName", out value)) @RealName = (String) value;
                if (values.TryGetValue("RegisterTime", out value)) @RegisterTime = (DateTime) value;
                if (values.TryGetValue("Salt", out value)) @Salt = (String) value;
                if (values.TryGetValue("SettleAccount", out value)) @SettleAccount = (Dictionary<Guid,SettleAccountTransaction>) value;
                if (values.TryGetValue("UserId", out value)) @UserId = (Guid) value;
                if (values.TryGetValue("Verified", out value)) @Verified = (Boolean) value;
                if (values.TryGetValue("VerifiedTime", out value)) @VerifiedTime = (Nullable<DateTime>) value;
            }

            public override System.String ToString()
            {
                return System.String.Format("UserState( Args={0} BankCards={1} Cellphone={2} ClientType={3} Closed={4} ContractId={5} Credential={6} CredentialNo={7} EncryptedPassword={8} EncryptedPaymentPassword={9} InviteBy={10} JBYAccount={11} LoginNames={12} Orders={13} OutletCode={14} PaymentSalt={15} RealName={16} RegisterTime={17} Salt={18} SettleAccount={19} UserId={20} Verified={21} VerifiedTime={22} )", @Args, @BankCards, @Cellphone, @ClientType, @Closed, @ContractId, @Credential, @CredentialNo, @EncryptedPassword, @EncryptedPaymentPassword, @InviteBy, @JBYAccount, @LoginNames, @Orders, @OutletCode, @PaymentSalt, @RealName, @RegisterTime, @Salt, @SettleAccount, @UserId, @Verified, @VerifiedTime);
            }
        
        public UserState() : 
                base("Yuyi.Jinyinmao.Domain.User")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["Args"] = this.Args;
            result["BankCards"] = this.BankCards;
            result["Cellphone"] = this.Cellphone;
            result["ClientType"] = this.ClientType;
            result["Closed"] = this.Closed;
            result["ContractId"] = this.ContractId;
            result["Credential"] = this.Credential;
            result["CredentialNo"] = this.CredentialNo;
            result["EncryptedPassword"] = this.EncryptedPassword;
            result["EncryptedPaymentPassword"] = this.EncryptedPaymentPassword;
            result["InviteBy"] = this.InviteBy;
            result["JBYAccount"] = this.JBYAccount;
            result["LoginNames"] = this.LoginNames;
            result["Orders"] = this.Orders;
            result["OutletCode"] = this.OutletCode;
            result["PaymentSalt"] = this.PaymentSalt;
            result["RealName"] = this.RealName;
            result["RegisterTime"] = this.RegisterTime;
            result["Salt"] = this.Salt;
            result["SettleAccount"] = this.SettleAccount;
            result["UserId"] = this.UserId;
            result["Verified"] = this.Verified;
            result["VerifiedTime"] = this.VerifiedTime;
            return result;
        }
        
        private void InitStateFields()
        {
            this.Args = new Dictionary<String,Object>();
            this.BankCards = new Dictionary<String,BankCard>();
            this.Cellphone = default(String);
            this.ClientType = default(Int64);
            this.Closed = default(Boolean);
            this.ContractId = default(Int64);
            this.Credential = default(Credential);
            this.CredentialNo = default(String);
            this.EncryptedPassword = default(String);
            this.EncryptedPaymentPassword = default(String);
            this.InviteBy = default(String);
            this.JBYAccount = new Dictionary<Guid,JBYAccountTransaction>();
            this.LoginNames = new List<String>();
            this.Orders = new Dictionary<Guid,Order>();
            this.OutletCode = default(String);
            this.PaymentSalt = default(String);
            this.RealName = default(String);
            this.RegisterTime = default(DateTime);
            this.Salt = default(String);
            this.SettleAccount = new Dictionary<Guid,SettleAccountTransaction>();
            this.UserId = default(Guid);
            this.Verified = default(Boolean);
            this.VerifiedTime = default(Nullable<DateTime>);
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            UserState input = ((UserState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            UserState input = ((UserState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            UserState result = new UserState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
}
namespace Yuyi.Jinyinmao.Domain.Products
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Yuyi.Jinyinmao.Domain.Dtos;
    using Orleans;
    using Yuyi.Jinyinmao.Domain;
    using System.Runtime.InteropServices;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.9.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("Yuyi.Jinyinmao.Domain.Products.JBYProduct")]
    public class JBYProductState : global::Orleans.GrainState, IJBYProductState
    {
        

            public String @Agreement1 { get; set; }

            public String @Agreement2 { get; set; }

            public Dictionary<String,Object> @Args { get; set; }

            public DateTime @EndSellTime { get; set; }

            public Int64 @FinancingSumAmount { get; set; }

            public Int32 @IssueNo { get; set; }

            public DateTime @IssueTime { get; set; }

            public Int64 @ProductCategory { get; set; }

            public Guid @ProductId { get; set; }

            public String @ProductName { get; set; }

            public String @ProductNo { get; set; }

            public Boolean @SoldOut { get; set; }

            public Nullable<DateTime> @SoldOutTime { get; set; }

            public DateTime @StartSellTime { get; set; }

            public Dictionary<Guid,JBYAccountTransactionInfo> @Transactions { get; set; }

            public Int64 @UnitPrice { get; set; }

            public DateTime @UpdateTime { get; set; }

            public Int32 @ValueDateMode { get; set; }

            public Int32 @Yield { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("Agreement1", out value)) @Agreement1 = (String) value;
                if (values.TryGetValue("Agreement2", out value)) @Agreement2 = (String) value;
                if (values.TryGetValue("Args", out value)) @Args = (Dictionary<String,Object>) value;
                if (values.TryGetValue("EndSellTime", out value)) @EndSellTime = (DateTime) value;
                if (values.TryGetValue("FinancingSumAmount", out value)) @FinancingSumAmount = value is Int32 ? (Int32)value : (Int64)value;
                if (values.TryGetValue("IssueNo", out value)) @IssueNo = value is Int64 ? (Int32)(Int64)value : (Int32)value;
                if (values.TryGetValue("IssueTime", out value)) @IssueTime = (DateTime) value;
                if (values.TryGetValue("ProductCategory", out value)) @ProductCategory = value is Int32 ? (Int32)value : (Int64)value;
                if (values.TryGetValue("ProductId", out value)) @ProductId = (Guid) value;
                if (values.TryGetValue("ProductName", out value)) @ProductName = (String) value;
                if (values.TryGetValue("ProductNo", out value)) @ProductNo = (String) value;
                if (values.TryGetValue("SoldOut", out value)) @SoldOut = (Boolean) value;
                if (values.TryGetValue("SoldOutTime", out value)) @SoldOutTime = (Nullable<DateTime>) value;
                if (values.TryGetValue("StartSellTime", out value)) @StartSellTime = (DateTime) value;
                if (values.TryGetValue("Transactions", out value)) @Transactions = (Dictionary<Guid,JBYAccountTransactionInfo>) value;
                if (values.TryGetValue("UnitPrice", out value)) @UnitPrice = value is Int32 ? (Int32)value : (Int64)value;
                if (values.TryGetValue("UpdateTime", out value)) @UpdateTime = (DateTime) value;
                if (values.TryGetValue("ValueDateMode", out value)) @ValueDateMode = value is Int64 ? (Int32)(Int64)value : (Int32)value;
                if (values.TryGetValue("Yield", out value)) @Yield = value is Int64 ? (Int32)(Int64)value : (Int32)value;
            }

            public override System.String ToString()
            {
                return System.String.Format("JBYProductState( Agreement1={0} Agreement2={1} Args={2} EndSellTime={3} FinancingSumAmount={4} IssueNo={5} IssueTime={6} ProductCategory={7} ProductId={8} ProductName={9} ProductNo={10} SoldOut={11} SoldOutTime={12} StartSellTime={13} Transactions={14} UnitPrice={15} UpdateTime={16} ValueDateMode={17} Yield={18} )", @Agreement1, @Agreement2, @Args, @EndSellTime, @FinancingSumAmount, @IssueNo, @IssueTime, @ProductCategory, @ProductId, @ProductName, @ProductNo, @SoldOut, @SoldOutTime, @StartSellTime, @Transactions, @UnitPrice, @UpdateTime, @ValueDateMode, @Yield);
            }
        
        public JBYProductState() : 
                base("Yuyi.Jinyinmao.Domain.Products.JBYProduct")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["Agreement1"] = this.Agreement1;
            result["Agreement2"] = this.Agreement2;
            result["Args"] = this.Args;
            result["EndSellTime"] = this.EndSellTime;
            result["FinancingSumAmount"] = this.FinancingSumAmount;
            result["IssueNo"] = this.IssueNo;
            result["IssueTime"] = this.IssueTime;
            result["ProductCategory"] = this.ProductCategory;
            result["ProductId"] = this.ProductId;
            result["ProductName"] = this.ProductName;
            result["ProductNo"] = this.ProductNo;
            result["SoldOut"] = this.SoldOut;
            result["SoldOutTime"] = this.SoldOutTime;
            result["StartSellTime"] = this.StartSellTime;
            result["Transactions"] = this.Transactions;
            result["UnitPrice"] = this.UnitPrice;
            result["UpdateTime"] = this.UpdateTime;
            result["ValueDateMode"] = this.ValueDateMode;
            result["Yield"] = this.Yield;
            return result;
        }
        
        private void InitStateFields()
        {
            this.Agreement1 = default(String);
            this.Agreement2 = default(String);
            this.Args = new Dictionary<String,Object>();
            this.EndSellTime = default(DateTime);
            this.FinancingSumAmount = default(Int64);
            this.IssueNo = default(Int32);
            this.IssueTime = default(DateTime);
            this.ProductCategory = default(Int64);
            this.ProductId = default(Guid);
            this.ProductName = default(String);
            this.ProductNo = default(String);
            this.SoldOut = default(Boolean);
            this.SoldOutTime = default(Nullable<DateTime>);
            this.StartSellTime = default(DateTime);
            this.Transactions = new Dictionary<Guid,JBYAccountTransactionInfo>();
            this.UnitPrice = default(Int64);
            this.UpdateTime = default(DateTime);
            this.ValueDateMode = default(Int32);
            this.Yield = default(Int32);
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            JBYProductState input = ((JBYProductState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            JBYProductState input = ((JBYProductState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            JBYProductState result = new JBYProductState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.9.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("Yuyi.Jinyinmao.Domain.Products.JBYProductWithdrawalManager")]
    public class JBYProductWithdrawalManagerState : global::Orleans.GrainState, IJBYProductWithdrawalManagerState
    {
        

            public Dictionary<Guid,JBYAccountTransactionInfo> @WithdrawalTransactions { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("WithdrawalTransactions", out value)) @WithdrawalTransactions = (Dictionary<Guid,JBYAccountTransactionInfo>) value;
            }

            public override System.String ToString()
            {
                return System.String.Format("JBYProductWithdrawalManagerState( WithdrawalTransactions={0} )", @WithdrawalTransactions);
            }
        
        public JBYProductWithdrawalManagerState() : 
                base("Yuyi.Jinyinmao.Domain.Products.JBYProductWithdrawalManager")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["WithdrawalTransactions"] = this.WithdrawalTransactions;
            return result;
        }
        
        private void InitStateFields()
        {
            this.WithdrawalTransactions = new Dictionary<Guid,JBYAccountTransactionInfo>();
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            JBYProductWithdrawalManagerState input = ((JBYProductWithdrawalManagerState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            JBYProductWithdrawalManagerState input = ((JBYProductWithdrawalManagerState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            JBYProductWithdrawalManagerState result = new JBYProductWithdrawalManagerState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
}
namespace Yuyi.Jinyinmao.Domain.Sagas
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Collections.Generic;
    using Orleans;
    using System.Runtime.InteropServices;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.9.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("Yuyi.Jinyinmao.Domain.Sagas.DepositSaga")]
    public class DepositSagaState : global::Orleans.GrainState, IDepositSagaState
    {
        

            public DateTime @BeginTime { get; set; }

            public Guid @SagaId { get; set; }

            public String @SagaType { get; set; }

            public DepositSagaInitData @InitData { get; set; }

            public DepositSagaStatus @Status { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("BeginTime", out value)) @BeginTime = (DateTime) value;
                if (values.TryGetValue("SagaId", out value)) @SagaId = (Guid) value;
                if (values.TryGetValue("SagaType", out value)) @SagaType = (String) value;
                if (values.TryGetValue("InitData", out value)) @InitData = (DepositSagaInitData) value;
                if (values.TryGetValue("Status", out value)) @Status = (DepositSagaStatus) value;
            }

            public override System.String ToString()
            {
                return System.String.Format("DepositSagaState( BeginTime={0} SagaId={1} SagaType={2} InitData={3} Status={4} )", @BeginTime, @SagaId, @SagaType, @InitData, @Status);
            }
        
        public DepositSagaState() : 
                base("Yuyi.Jinyinmao.Domain.Sagas.DepositSaga")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["BeginTime"] = this.BeginTime;
            result["SagaId"] = this.SagaId;
            result["SagaType"] = this.SagaType;
            result["InitData"] = this.InitData;
            result["Status"] = this.Status;
            return result;
        }
        
        private void InitStateFields()
        {
            this.BeginTime = default(DateTime);
            this.SagaId = default(Guid);
            this.SagaType = default(String);
            this.InitData = new DepositSagaInitData();
            this.Status = default(DepositSagaStatus);
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            DepositSagaState input = ((DepositSagaState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            DepositSagaState input = ((DepositSagaState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            DepositSagaState result = new DepositSagaState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 414
#pragma warning restore 649
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
