//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace Yuyi.Jinyinmao.Domain
{
    using System;
    using System.Collections.Generic;
    using System.Collections;
    using Orleans.CodeGeneration;
    using Orleans;
    using System.Runtime.InteropServices;
    using System.Runtime.Serialization;
    using Orleans.Runtime;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("Yuyi.Jinyinmao.Domain.Yuyi.Jinyinmao.Domain.Cellphone")]
    public class CellphoneState : global::Orleans.CodeGeneration.GrainState, ICellphoneState
    {
        

            public String @Cellphone { get; set; }

            public Boolean @Registered { get; set; }

            public Nullable<Guid> @UserId { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("Cellphone", out value)) @Cellphone = (String) value;
                if (values.TryGetValue("Registered", out value)) @Registered = (Boolean) value;
                if (values.TryGetValue("UserId", out value)) @UserId = (Nullable<Guid>) value;
            }

            public override System.String ToString()
            {
                return System.String.Format("CellphoneState( Cellphone={0} Registered={1} UserId={2} )", @Cellphone, @Registered, @UserId);
            }
        
        public CellphoneState() : 
                base("Yuyi.Jinyinmao.Domain.Cellphone")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["Cellphone"] = this.Cellphone;
            result["Registered"] = this.Registered;
            result["UserId"] = this.UserId;
            return result;
        }
        
        private void InitStateFields()
        {
            this.Cellphone = default(String);
            this.Registered = default(Boolean);
            this.UserId = default(Nullable<Guid>);
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            CellphoneState input = ((CellphoneState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            CellphoneState input = ((CellphoneState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            CellphoneState result = new CellphoneState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("Yuyi.Jinyinmao.Domain.Yuyi.Jinyinmao.Domain.JBYAccount")]
    public class JBYAccountState : global::Orleans.CodeGeneration.GrainState, IJBYAccountState
    {
        

            public Guid @Id { get; set; }

            public IList<Int32> @InterestRate { get; set; }

            public IList<TransactionInfo> @Transactions { get; set; }

            public Guid @UserId { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("Id", out value)) @Id = (Guid) value;
                if (values.TryGetValue("InterestRate", out value)) @InterestRate = (IList<Int32>) value;
                if (values.TryGetValue("Transactions", out value)) @Transactions = (IList<TransactionInfo>) value;
                if (values.TryGetValue("UserId", out value)) @UserId = (Guid) value;
            }

            public override System.String ToString()
            {
                return System.String.Format("JBYAccountState( Id={0} InterestRate={1} Transactions={2} UserId={3} )", @Id, @InterestRate, @Transactions, @UserId);
            }
        
        public JBYAccountState() : 
                base("Yuyi.Jinyinmao.Domain.JBYAccount")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["Id"] = this.Id;
            result["InterestRate"] = this.InterestRate;
            result["Transactions"] = this.Transactions;
            result["UserId"] = this.UserId;
            return result;
        }
        
        private void InitStateFields()
        {
            this.Id = default(Guid);
            this.InterestRate = default(IList<Int32>);
            this.Transactions = default(IList<TransactionInfo>);
            this.UserId = default(Guid);
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            JBYAccountState input = ((JBYAccountState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            JBYAccountState input = ((JBYAccountState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            JBYAccountState result = new JBYAccountState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("Yuyi.Jinyinmao.Domain.Yuyi.Jinyinmao.Domain.SettlementAccount")]
    public class SettlementAccountState : global::Orleans.CodeGeneration.GrainState, ISettlementAccountState
    {
        

            public Guid @Id { get; set; }

            public IList<TransactionInfo> @Transactions { get; set; }

            public Guid @UserId { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("Id", out value)) @Id = (Guid) value;
                if (values.TryGetValue("Transactions", out value)) @Transactions = (IList<TransactionInfo>) value;
                if (values.TryGetValue("UserId", out value)) @UserId = (Guid) value;
            }

            public override System.String ToString()
            {
                return System.String.Format("SettlementAccountState( Id={0} Transactions={1} UserId={2} )", @Id, @Transactions, @UserId);
            }
        
        public SettlementAccountState() : 
                base("Yuyi.Jinyinmao.Domain.SettlementAccount")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["Id"] = this.Id;
            result["Transactions"] = this.Transactions;
            result["UserId"] = this.UserId;
            return result;
        }
        
        private void InitStateFields()
        {
            this.Id = default(Guid);
            this.Transactions = default(IList<TransactionInfo>);
            this.UserId = default(Guid);
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            SettlementAccountState input = ((SettlementAccountState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            SettlementAccountState input = ((SettlementAccountState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            SettlementAccountState result = new SettlementAccountState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [SerializableAttribute()]
    [global::Orleans.CodeGeneration.GrainStateAttribute("Yuyi.Jinyinmao.Domain.Yuyi.Jinyinmao.Domain.User")]
    public class UserState : global::Orleans.CodeGeneration.GrainState, IUserState
    {
        

            public ICommandStore @CommandStore { get; set; }

            public IEventStore @EventStore { get; set; }

            public Guid @Id { get; set; }

            public String @Args { get; set; }

            public String @Cellphone { get; set; }

            public Int64 @ClientType { get; set; }

            public Int64 @ContractId { get; set; }

            public Credential @Credential { get; set; }

            public String @CredentialNo { get; set; }

            public String @EncryptedPassword { get; set; }

            public String @EncryptedPaymentPassword { get; set; }

            public String @InviteBy { get; set; }

            public IJBYAccount @JBYAccount { get; set; }

            public List<String> @LoginNames { get; set; }

            public String @OutletCode { get; set; }

            public String @PaymentSalt { get; set; }

            public String @RealName { get; set; }

            public DateTime @RegisterTime { get; set; }

            public String @Salt { get; set; }

            public ISettlementAccount @SettlementAccount { get; set; }

            public Boolean @Verified { get; set; }

            public Nullable<DateTime> @VerifiedTime { get; set; }

            public override void SetAll(System.Collections.Generic.IDictionary<string,object> values)
            {   
                object value;
                if (values == null) { InitStateFields(); return; }
                if (values.TryGetValue("CommandStore", out value)) @CommandStore = (ICommandStore) value;
                if (values.TryGetValue("EventStore", out value)) @EventStore = (IEventStore) value;
                if (values.TryGetValue("Id", out value)) @Id = (Guid) value;
                if (values.TryGetValue("Args", out value)) @Args = (String) value;
                if (values.TryGetValue("Cellphone", out value)) @Cellphone = (String) value;
                if (values.TryGetValue("ClientType", out value)) @ClientType = value is Int32 ? (Int32)value : (Int64)value;
                if (values.TryGetValue("ContractId", out value)) @ContractId = value is Int32 ? (Int32)value : (Int64)value;
                if (values.TryGetValue("Credential", out value)) @Credential = (Credential) value;
                if (values.TryGetValue("CredentialNo", out value)) @CredentialNo = (String) value;
                if (values.TryGetValue("EncryptedPassword", out value)) @EncryptedPassword = (String) value;
                if (values.TryGetValue("EncryptedPaymentPassword", out value)) @EncryptedPaymentPassword = (String) value;
                if (values.TryGetValue("InviteBy", out value)) @InviteBy = (String) value;
                if (values.TryGetValue("JBYAccount", out value)) @JBYAccount = (IJBYAccount) value;
                if (values.TryGetValue("LoginNames", out value)) @LoginNames = (List<String>) value;
                if (values.TryGetValue("OutletCode", out value)) @OutletCode = (String) value;
                if (values.TryGetValue("PaymentSalt", out value)) @PaymentSalt = (String) value;
                if (values.TryGetValue("RealName", out value)) @RealName = (String) value;
                if (values.TryGetValue("RegisterTime", out value)) @RegisterTime = (DateTime) value;
                if (values.TryGetValue("Salt", out value)) @Salt = (String) value;
                if (values.TryGetValue("SettlementAccount", out value)) @SettlementAccount = (ISettlementAccount) value;
                if (values.TryGetValue("Verified", out value)) @Verified = (Boolean) value;
                if (values.TryGetValue("VerifiedTime", out value)) @VerifiedTime = (Nullable<DateTime>) value;
            }

            public override System.String ToString()
            {
                return System.String.Format("UserState( CommandStore={0} EventStore={1} Id={2} Args={3} Cellphone={4} ClientType={5} ContractId={6} Credential={7} CredentialNo={8} EncryptedPassword={9} EncryptedPaymentPassword={10} InviteBy={11} JBYAccount={12} LoginNames={13} OutletCode={14} PaymentSalt={15} RealName={16} RegisterTime={17} Salt={18} SettlementAccount={19} Verified={20} VerifiedTime={21} )", @CommandStore, @EventStore, @Id, @Args, @Cellphone, @ClientType, @ContractId, @Credential, @CredentialNo, @EncryptedPassword, @EncryptedPaymentPassword, @InviteBy, @JBYAccount, @LoginNames, @OutletCode, @PaymentSalt, @RealName, @RegisterTime, @Salt, @SettlementAccount, @Verified, @VerifiedTime);
            }
        
        public UserState() : 
                base("Yuyi.Jinyinmao.Domain.User")
        {
            this.InitStateFields();
        }
        
        public override System.Collections.Generic.IDictionary<string, object> AsDictionary()
        {
            System.Collections.Generic.Dictionary<string, object> result = new System.Collections.Generic.Dictionary<string, object>();
            result["CommandStore"] = this.CommandStore;
            result["EventStore"] = this.EventStore;
            result["Id"] = this.Id;
            result["Args"] = this.Args;
            result["Cellphone"] = this.Cellphone;
            result["ClientType"] = this.ClientType;
            result["ContractId"] = this.ContractId;
            result["Credential"] = this.Credential;
            result["CredentialNo"] = this.CredentialNo;
            result["EncryptedPassword"] = this.EncryptedPassword;
            result["EncryptedPaymentPassword"] = this.EncryptedPaymentPassword;
            result["InviteBy"] = this.InviteBy;
            result["JBYAccount"] = this.JBYAccount;
            result["LoginNames"] = this.LoginNames;
            result["OutletCode"] = this.OutletCode;
            result["PaymentSalt"] = this.PaymentSalt;
            result["RealName"] = this.RealName;
            result["RegisterTime"] = this.RegisterTime;
            result["Salt"] = this.Salt;
            result["SettlementAccount"] = this.SettlementAccount;
            result["Verified"] = this.Verified;
            result["VerifiedTime"] = this.VerifiedTime;
            return result;
        }
        
        private void InitStateFields()
        {
            this.CommandStore = default(ICommandStore);
            this.EventStore = default(IEventStore);
            this.Id = default(Guid);
            this.Args = default(String);
            this.Cellphone = default(String);
            this.ClientType = default(Int64);
            this.ContractId = default(Int64);
            this.Credential = default(Credential);
            this.CredentialNo = default(String);
            this.EncryptedPassword = default(String);
            this.EncryptedPaymentPassword = default(String);
            this.InviteBy = default(String);
            this.JBYAccount = default(IJBYAccount);
            this.LoginNames = new List<String>();
            this.OutletCode = default(String);
            this.PaymentSalt = default(String);
            this.RealName = default(String);
            this.RegisterTime = default(DateTime);
            this.Salt = default(String);
            this.SettlementAccount = default(ISettlementAccount);
            this.Verified = default(Boolean);
            this.VerifiedTime = default(Nullable<DateTime>);
        }
        
        [global::Orleans.CodeGeneration.CopierMethodAttribute()]
        public static object _Copier(object original)
        {
            UserState input = ((UserState)(original));
            return input.DeepCopy();
        }
        
        [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
        public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            UserState input = ((UserState)(original));
            input.SerializeTo(stream);
        }
        
        [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
        public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            UserState result = new UserState();
            result.DeserializeFrom(stream);
            return result;
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
